### ISSUE TITLE
VSCode plugin

### ISSUE THREAD

**Issue by mithandir** [moyix/fauxpilot#1]
Hi,I tried using the VSCode plugin using the supplied configuration, but the plugin throws the following error:

[INFO] [auth] [2022-08-03T06:47:46.784Z] Invalid copilot token: missing token: 403 
[ERROR] [default] [2022-08-03T06:47:46.787Z] GitHub Copilot could not connect to server. Extension activation failed: "User not authorized"

Do we need a GitHub Copilot subscription to get a working token?

**Comment by moyix** [comment]
It appears so unfortunately! It is probably possible to bypass this by changing the code of the extension, but that's going a bit beyond what I'm comfortable with.

You may want to check out this extension developed by some of my colleagues, which also talks to the OpenAI API, and so should be easy to use with FauxPilot:

https://github.com/synoet/Pincer/tree/main/extension

However, it needs a bit of updating now that the InlineCompletions API has been finalized (it was originally written for the VSCode beta). You'll probably also want to tear out the telemetry that we added for our user study.

**Comment by Xelef2000** [comment]
I think [this vs code extension](https://github.com/hieunc229/copilot-clone) could be modified easily for fauxpilot.

**Comment by Venthe** [comment]
After small modifications I've managed to get the plugin to ask the server for completions, though I am getting 
```
[2022-08-07 17:16:38,353] ERROR in app: Exception on /v1/engines/codegen/completions [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1760, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1758, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1734, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/python-docker/app.py", line 252, in completions
    response=codegen(data),
  File "/python-docker/app.py", line 234, in __call__
    completion, choices = self.generate(data)
  File "/python-docker/app.py", line 146, in generate
    result = self.client.infer(model_name, inputs)
  File "/usr/local/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 1322, in infer
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] Request for unknown model: 'fastertransformer' is not found
172.21.0.1 - - [07/Aug/2022 17:16:38] "POST /v1/engines/codegen/completions HTTP/1.1" 500 -
```

Any ideas?

**Comment by Venthe** [comment]
After some modifications to the VSCode plugin; I've managed to bypass the token and have a SINGLE autocompletion. And I couldn't manage to repeat that ever since :(

**Comment by Venthe** [comment]
I should have a barebones extension (code, I dunno how to upload it to marketplace) in a few hours, just teaching myself how to do so

**Comment by Venthe** [comment]
https://github.com/Venthe/vscode-fauxpilot

This is a (very) basic implementation; as I've just hacked around. It is NOT published, but it does work :)

@moyix if I would wish to publish it and work on it; can I use the name Fauxpilot? Or would you rather prefer for me not to use that name?

**Comment by moyix** [comment]
Sure, feel free to use the name!

**Comment by LukyBruce** [comment]
Can we update this plugin in the readme, the vscode for github copilot just does not work.

**Comment by moyix** [comment]
Do you mean it doesn't work without having a valid token for Copilot? Or is something going wrong after that too?

**Comment by xinlnix** [comment]
> Do you mean it doesn't work without having a valid token for Copilot? Or is something going wrong after that too?

Yes, I also have trouble to use the Copilot vscode plugin.

**Comment by linonetwo** [comment]
@Venthe what does max token and suggestion delay mean in your plugin? These are not very clear in the Readme.

**Comment by moyix** [comment]
> > Do you mean it doesn't work without having a valid token for Copilot? Or is something going wrong after that too?
> 
> Yes, I also have trouble to use the Copilot vscode plugin.

I will try to find some time to test again with the most recent Copilot. Last time I checked there were issues with the tokenizers between Copilot and CodeGen being slightly different, so Copilot sometimes makes requests that are too long for CodeGen – I think this can be fixed by replacing the `vocab.bpe` and `tokenizer.json` files in the VSCode plugin directory with the CodeGen versions found here: https://github.com/moyix/fauxpilot/tree/main/copilot_proxy/cgtok/openai_format

I have not tested this though, just very short on time now that school is back in session :(

**Comment by petronny** [comment]
>  [INFO] [auth] [2022-08-03T06:47:46.784Z] Invalid copilot token: missing token: 403
[ERROR] [default] [2022-08-03T06:47:46.787Z] GitHub Copilot could not connect to server. Extension activation failed: "User not authorized"

I can help with this since it also appears in the official vim plugin.

It uses `https://api.github.com/copilot_internal/v2/token` to get a token.
So we can hack the address to `http://localhost:5000/copilot_internal/v2/token` to bypass this step.

It should return a json string with `token` and `expires_at`. But I don't know the format of `expires_at` since I have no subscription to copilot.

**Comment by fdegier** [comment]
The next release of the GitLab VS code extension will have support for FauxPilot. Welcoming contributions 😄

Extension:
https://gitlab.com/gitlab-org/gitlab-vscode-extension

Merge Request:
https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/merge_requests/648

**Comment by Venthe** [comment]
> @Venthe what does max token and suggestion delay mean in your plugin? These are not very clear in the Readme.
> 
> And default max token is 4, is pretty weird, I think code snippet need at least 200 token.

Hey, sorry for missing this comment. To be completely honest, I do not remember why I've set it this way. This is / was  a rough implementation only; just to have something working.

Delay: This sets the time for the debounce-like mechanism
Max token: I do not know, but see `https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them` . As for the value 4, it seems low indeed; I'll update the defaults

**Comment by shadowwider** [comment]
After testing several extensions I ended up going with github copilot. It seems more faster,more features and smarter ，like set different stopwords in different situations. 
And I find a way to use it without subscribe， you can try. Like moyix said we must to rewrite raw extensions code for skip the boring authentication process. 
1. set github copilot extension config 
```json
"github.copilot.advanced": {
        "model": "fastertransformer",
        "debug.overrideEngine": "codegen",
        "debug.testOverrideProxyUrl": "http://192.168.1.161:5000",
        "debug.overrideProxyUrl": "http://192.168.1.161:5000"    
    },

```
2. Use the attached js file to override copilot raw file on `~\.vscode\extensions\github.copilot-**1.54.7077**\dist\extension.js`（you can do it by youself）
3. Set copilot to Ignore updates or you will lost the Hack code

**Comment by pai4451** [comment]
Hi @shadowwider, where is the attached js? I also want to use GitHub copilot extension with fauxpilot server.

**Comment by shadowwider** [comment]
> Hi @shadowwider, where is the attached js? I also want to use GitHub copilot extension with fauxpilot server.

https://github.com/shadowwider/brook/releases/download/v1/extension.js 
you can try this

**Comment by dewacandra4** [comment]
I encounter this error while using the copilot plugin `[ERROR] [streamChoices] Error parsing JSON stream data. ` 
Is there anything that I missing?

**Comment by thakkarparth007** [comment]
The Copilot extension needs well formatted streaming response, but the copilot_proxy code seems to return badly formatted data. Here's an example of the streamed response:

```
data: data: {"id": "cmpl-6TMRfgynXT3wpdrNOVZgS4is5DadC", "model": "codegen", "object": "text_completion", "created": 1671816259, "choices": [{"text": ",\n        )\n        return self._s", "index": 0, "finish_reason": "length", "logprobs": null}], "usage": {"completion_tokens": 10, "prompt_tokens": 1, "total_tokens": 11}}
data: 
data: 

data: data: [DONE]
data: 
data: 
```

As you can see, there's `data: data: {..actual_json_stuff..}`, whereas it should just be `data: {..actual_json_stuff..}`. I'm unable to determine what's adding the first "data:". The second "data:" is coming from code in utils/code_gen.py. Removing the `data: ` prefix there seems to fix this issue -- I do see inline suggestions.

However, I think we need to make some more changes on the backend (preferrably in the fastertransformer backend, otherwise at least in the proxy) for better integration with the Copilot extension (if that's desired).

For instance, currently the "stop tokens" logic is not correct ( #85 ), because of which the client gets an overly long response. In my case, 500 tokens were being returned, including logprobs. The client then just trims the result with appropriate stop tokens. This results in wasted compute and poor latency. Ideally, the stopword logic would be correctly handled in the fastertransformer backend itself, however that's not happening.

**Comment by brandonvessel** [comment]
Hello all. The comments above have been very helpful in setting up the Copilot extension. I managed to get it to work with my instance and figured I would combine the steps I used (this is for Windows. Linux installation is similar, just different locations):

1. Go through the standard Fauxpilot server setup. If the docker containers are running and are query-able with curl, move ahead. I used @frederisk's fauxpilot-windows fork for the launch.ps1 and setup.ps1 scripts. More or less, it's the same. (source: https://github.com/Frederisk/fauxpilot-windows)

2. Install GitHub Copilot into VSCode (we will defang some of this later).

3. Add the GitHub copilot overrides to the settings.json file. These steps are outlined for this in https://github.com/fauxpilot/fauxpilot/blob/main/documentation/client.md (Copilot Plugin).

4. @petronny has some steps for getting VIM to work with Fauxpilot (https://github.com/fauxpilot/fauxpilot/discussions/72). We will use these steps to fix the VSCode version. Find and replace the following strings in the "%userprofile%\.vscode\extensions\github.copilot-#.##.####\dist\extension.js" file:
- https://api.github.com/copilot_internal -> http://127.0.0.1:5000/copilot_internal
- https://copilot-proxy.githubusercontent.com -> http://127.0.0.1:5000

This is essentially a manual override for the GitHub token retrieval to use our local instance instead.

5. Not all telemetry is removed from the extension. Removal of all the telemetry may violate the TOS for Copilot. Do so at your own discretion. It will, however, not send your code to Microsoft.

6. Make sure your extensions are not set to automatically update or the extension.js changes will be reverted when GitHub Copilot updates.

7. Copilot should behave as usual, but is now using Fauxpilot's docker setup for token generation instead. There are occasional issues with token amount as mentioned above, but these are the steps I used to get it at least running.

**Comment by hsooya** [comment]
@Venthe First of all thanks for making the plugin! It worked for me. I was looking at the source code for your plugin. I was wondering how much of the plugin you have adapted from Open AI Co-pilot plugin. The reason I was asking this is merely coz I want to make sure that there is no way that the extension can contact the OpenAI servers due to security policy of being able to use it at work. 

For example, even when we set the server address to the local codegen one using config in the OpenAI co-pilot plugin ( that is used for recommendation generation) , there were traces of code responsible for token handling that were contacting Github. 

I'm gonna try to read more about VSCode plugins in the meantime. Again, thanks for your plugin.

**Comment by Venthe** [comment]
> @Venthe First of all thanks for making the plugin! It worked for me. I was looking at the source code for your plugin. I was wondering how much of the plugin you have adapted from Open AI Co-pilot plugin. The reason I was asking this is merely coz I want to make sure that there is no way that the extension can contact the OpenAI servers due to security policy of being able to use it at work. 
> 
> For example, even when we set the server address to the local codegen one using config in the OpenAI co-pilot plugin ( that is used for recommendation generation) , there were traces of code responsible for token handling that were contacting Github. 
> 
> I'm gonna try to read more about VSCode plugins in the meantime. Again, thanks for your plugin. 

Not at all, happy to provide.

It was - and is - basically a hack done in few hours (and my first plugin for vscode); and the only parts that I've been "using" from the other repo was the actual API call. At the time there was no option to use fauxpilot in Code without severe tinkering with original copilot plugin (basically removing the token handling and more as far as I remember).

At this point the plug-in for me is done as it is working fine; I'm only improving it as per feature requests though considering that Gitlab has made their own version of fauxpilot client, i believe that mine is quite obsolete at this point

**Comment by fdegier** [comment]
Hi @Venthe 

> At this point the plug-in for me is done as it is working fine; I'm only improving it as per feature requests though considering that Gitlab has made their own version of fauxpilot client, i believe that mine is quite obsolete at this point

GitLab actually (very unfortunately) dropped support for FauxPilot https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/merge_requests/697

It might be worth adopting some of the mechanisms from that plugin such as the debounce mechanism, yours doesn't actually work as intended. I think it would be a good idea to adopt your plugin into the FauxPilot organization since you have the plugin already published on the marketplace. WDYT?

**Comment by Venthe** [comment]
@fdegier 

> GitLab actually (very unfortunately) dropped support for FauxPilot https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/merge_requests/697

Good to know, thanks

> It might be worth adopting some of the mechanisms from that plugin such as the debounce mechanism, yours doesn't actually work as intended.

Hahah, yeah, it does not. I've cobbled a dirty solution because the only library that I've worked with that had debounce was heavy, and I needed it to "at least" work. I knew that it will catch up to me:)

> I think it would be a good idea to adopt your plugin into the FauxPilot organization since you have the plugin already published on the marketplace. WDYT?

No problem with that; I can keep it in my namespace or move it to org; but this is not ultimately question for me I believe. My only "requirement" is for it to stay MIT or similar license.

> (...) ideally the plugin for FauxPilot should adopt the interface from OpenAI 

Please bear in mind; that I have zero understanding about the API - that's why I've specifically noted that it was a quick job, the plug-in. I'm happy to contribute, but I'll need at least some guidance in that regard.

**Comment by AdithyaRamanChippa** [comment]
hello @brandonvessel  I am not able to find this occurrence https://api.github.com/copilot_internal in my extension.js file

**Comment by brandonvessel** [comment]
@AdithyaRamanChippa I have observed this change as well with the recent changes to the extension. This combability was originally confirmed by me on version v1.77.9225 of the GitHub Copilot extension.

**Comment by tolsadus** [comment]
> After testing several extensions I ended up going with github copilot. It seems more faster,more features and smarter ，like set different stopwords in different situations. And I find a way to use it without subscribe， you can try. Like moyix said we must to rewrite raw extensions code for skip the boring authentication process.
> 
> 1. set github copilot extension config
> 
> ```json
> "github.copilot.advanced": {
>         "model": "fastertransformer",
>         "debug.overrideEngine": "codegen",
>         "debug.testOverrideProxyUrl": "http://192.168.1.161:5000",
>         "debug.overrideProxyUrl": "http://192.168.1.161:5000"    
>     },
> ```
> 
> 2. Use the attached js file to override copilot raw file on `~\.vscode\extensions\github.copilot-1.54.7077\dist\extension.js`（you can do it by youself, the file I provided only for version 1.54.7077 ）
> 3. Set copilot to Ignore updates or you will lost the Hack code
> 
> Another thing is I must change [this](https://github.com/moyix/fauxpilot/blob/e5825da8be767c1908f64ed251d1a134fcb291c0/copilot_proxy/utils/codegen.py#L233) to `yield f'{json.dumps(completion)}`. Seems stream fomart are different.

What are the changes you made in the extension.js, do you have a diff maybe? I'll like to implement this for 1.143.0

**Comment by shadowwider** [comment]
> > After testing several extensions I ended up going with github copilot. It seems more faster,more features and smarter ，like set different stopwords in different situations. And I find a way to use it without subscribe， you can try. Like moyix said we must to rewrite raw extensions code for skip the boring authentication process.
> > 
> > 1. set github copilot extension config
> > 
> > ```json
> > "github.copilot.advanced": {
> >         "model": "fastertransformer",
> >         "debug.overrideEngine": "codegen",
> >         "debug.testOverrideProxyUrl": "http://192.168.1.161:5000",
> >         "debug.overrideProxyUrl": "http://192.168.1.161:5000"    
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Use the attached js file to override copilot raw file on `~\.vscode\extensions\github.copilot-1.54.7077\dist\extension.js`（you can do it by youself, the file I provided only for version 1.54.7077 ）
> > 3. Set copilot to Ignore updates or you will lost the Hack code
> > 
> > Another thing is I must change [this](https://github.com/moyix/fauxpilot/blob/e5825da8be767c1908f64ed251d1a134fcb291c0/copilot_proxy/utils/codegen.py#L233) to `yield f'{json.dumps(completion)}`. Seems stream fomart are different.
> 
> What are the changes you made in the extension.js, do you have a diff maybe? I'll like to implement this for 1.143.0

I'm sorry, I haven't had a new version for a long time and I've forgotten about it now. Maybe you could try running a git diff between my file and the corresponding official version's source file to see what changes were made; there should be very few. It's just that I removed a few parts for verifying accounts, which doesn't affect the basic logic
